name: Scrape Jumbo y actualizar Google Sheets

on:
  workflow_dispatch: {}
  schedule:
    # Todos los lunes a las 15:00 UTC ≈ 11:00 en Chile (invierno)
    - cron: "0 15 * * 1"

jobs:
  run-scraper:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    # Puedes dejar el SHEET_ID aquí o moverlo a Secrets si prefieres
    env:
      SHEET_ID: 14Rn3q0vhWAcxHxYTCzfuDOtk3Y9cKnJlglnMb-eHr14
      CHROME_BIN: /usr/bin/chromium

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar Chromium & Chromedriver
        shell: bash
        run: |
          set -e
          sudo apt-get update
          # Chromium suele instalarse como snap; en esta imagen hay un binario real en /usr/bin/chromium
          sudo apt-get install -y chromium-browser || sudo apt-get install -y chromium || true
          # Chromedriver (el paquete varía por imagen)
          sudo apt-get install -y chromium-chromedriver || sudo apt-get install -y chromium-driver || true

      - name: Diagnóstico de binarios (opcional)
        shell: bash
        run: |
          echo "CHROME_BIN=$CHROME_BIN"
          command -v "$CHROME_BIN" || true
          "$CHROME_BIN" --version || true
          command -v chromedriver || true
          chromedriver --version || true
          ls -l /usr/bin/chrom* || true
          ls -l /snap/bin/chrom* || true

      - name: Instalar dependencias
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar scraper
        env:
          SHEET_ID: ${{ env.SHEET_ID }}
          CHROME_BIN: ${{ env.CHROME_BIN }}
          # Fallback: usa GCP_SHEETS_CREDENTIALS si existe; si no, intenta GCP_SHEETS_CREDENTIALS_JSON
          GCP_SHEETS_CREDENTIALS: ${{ secrets.GCP_SHEETS_CREDENTIALS != '' && secrets.GCP_SHEETS_CREDENTIALS || secrets.GCP_SHEETS_CREDENTIALS_JSON }}
        run: |
          # Validación explícita para evitar correr sin credenciales
          if [ -z "${GCP_SHEETS_CREDENTIALS}" ]; then
            echo "ERROR: GCP_SHEETS_CREDENTIALS está vacío. Define el secret en Settings → Secrets and variables → Actions." >&2
            exit 1
          fi
          python scraper.py
